### ISSUE TITLE
Fails to parse Stylesheet with invalid characters between rules

### ISSUE THREAD

**Issue by capricorn86** [capricorn86/happy-dom#1036]
Invalid CSS selector exception thrown for
```css
	.container1 {
		background: yellow;
	}
;

	.container2 {
		background: red;
	}

	.container3 {
		background: pink;
	}
```
