### ISSUE TITLE
CSS parsing incorrectly when last rule is a setting of a CSS variable w/o a semicolon

### ISSUE THREAD

**Issue by petejodo** [capricorn86/happy-dom#670]
**Describe the bug**
Some CSS tools such as tailwind outputs their CSS files minified. The minified CSS strips semicolons
from the last rules in a block. Here's a small snippet of such CSS

```css
*,:after,:before{box-sizing:border-box;border:0 solid #e5e7eb}:after,:before{--tw-content:""}html{line-height:1.5;-webkit-text-size-adjust:100%;-moz-tab-size:4;-o-tab-size:4;tab-size:4;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-feature-settings:normal}
```

I noticed some issues with the styles I expected and so I was stepping through some code and noticed that [here in CSSStyleDeclarationElementStyle](https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/css/declaration/utilities/CSSStyleDeclarationElementStyle.ts#L236-L241) that the value of `cssValue` was `0display` and then when looking more closely at what's stored in `properties`, a lot of the values were messed up. At first I thought it was because all the last rules in a block were missing semicolons and so I formatted my css file and added semicolons to every last line and confirmed that the styles I was now getting back were correct.

**However**, when I tried to write a simple example to repro it, I couldn't. After some more digging I noticed the following block in my CSS file:

```css
*,::backdrop,:after,:before{--tw-border-spacing-x:0;--tw-border-spacing-y:0;--tw-translate-x:0;--tw-translate-y:0;--tw-rotate:0;--tw-skew-x:0;--tw-skew-y:0;--tw-scale-x:1;--tw-scale-y:1;--tw-pan-x: ;--tw-pan-y: ;--tw-pinch-zoom: ;--tw-scroll-snap-strictness:proximity;--tw-ordinal: ;--tw-slashed-zero: ;--tw-numeric-figure: ;--tw-numeric-spacing: ;--tw-numeric-fraction: ;--tw-ring-inset: ;--tw-ring-offset-width:0px;--tw-ring-offset-color:#fff;--tw-ring-color:#3b82f680;--tw-ring-offset-shadow:0 0 #0000;--tw-ring-shadow:0 0 #0000;--tw-shadow:0 0 #0000;--tw-shadow-colored:0 0 #0000;--tw-blur: ;--tw-brightness: ;--tw-contrast: ;--tw-grayscale: ;--tw-hue-rotate: ;--tw-invert: ;--tw-saturate: ;--tw-sepia: ;--tw-drop-shadow: ;--tw-backdrop-blur: ;--tw-backdrop-brightness: ;--tw-backdrop-contrast: ;--tw-backdrop-grayscale: ;--tw-backdrop-hue-rotate: ;--tw-backdrop-invert: ;--tw-backdrop-opacity: ;--tw-backdrop-saturate: ;--tw-backdrop-sepia: }
```

Notice how the last rule is the setting of a CSS variable w/o a semicolon `--tw-backdrop-sepia: }`. By adding a semicolon, so `--tw-backdrop-sepia: ;}`, I noticed just that 1 change also fixed the issue I was seeing.

**To Reproduce**
1. Add the CSS `*{--tw-backdrop-sepia: }div{display:flex}` and render a div
2. Call `window.getComputedStyle` with the rendered div
3. See that the returned object's value for `display` is `block`
4. Add a semicolon such that the CSS now looks like `*{--tw-backdrop-sepia: ;}div{display:flex}` and retry the above steps
5. Note the returned object's value for `display` is now `flex`

**NOTE** For the bug to happen, the selectors have to match with the element in question so if the CSS in the repo example above was this instead: `span{--tw-backdrop-sepia: }div{display:flex}`, then the issue would not occur.

**Expected behavior**
The returned value for `display` is `flex`

**Additional context**
Here is the above repro steps in my test code using react-testing-library

```tsx
const style = document.createElement('style');
    style.innerHTML = "*{--tw-backdrop-sepia: }div{display:flex}";
    document.body.appendChild(style);

    const { container } = render(<div />);
    console.log(window.getComputedStyle(container.firstElementChild!).display)
```
